on:
  push:
    paths-ignore:
      - "backstage/**"

name: Terraform
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: sturlabragason/terraform_state_artifact@v1
        with:
            encryptionkey: ${{ secrets.encryptionkey }}
        env:
          TF_VAR_az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
          TF_VAR_GITHUB_TOKEN: ${{ secrets.TOKEN }}